version: "3.8"

services:
  thread:
    build: ./thread
    ports:
      - "80:80"
    networks:
      - forum-net

  sender:
    build: ./sender
    ports:
      - "8080:80"
    networks:
      - forum-net

networks:
  forum-net:
    driver: bridge
