version: "3.8"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - forum-net
    environment:
      - PORT=3000

  thread:
    build: ./thread
    ports:
      - "80:80"
    networks:
      - forum-net
    depends_on:
      - api

  sender:
    build: ./sender
    ports:
      - "8080:80"
    networks:
      - forum-net
    depends_on:
      - api

networks:
  forum-net:
    driver: bridge
