version: '3.8'

services:
  db:
    image: postgres:15
    container_name: forum-db
    environment:
      POSTGRES_USER: forum_user
      POSTGRES_PASSWORD: forum_pass
      POSTGRES_DB: forum_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - internal
    restart: unless-stopped

  api:
    build:
      context: ./api
    container_name: forum-api
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: forum_user
      DB_PASSWORD: forum_pass
      DB_NAME: forum_db
    networks:
      - internal
    restart: unless-stopped

  thread:
    build:
      context: ./thread
    container_name: forum-thread
    depends_on:
      - api
    ports:
      - "80:80"
    networks:
      - internal
    restart: unless-stopped

  sender:
    build:
      context: ./sender
    container_name: forum-sender
    depends_on:
      - api
    ports:
      - "8080:80"
    networks:
      - internal
    restart: unless-stopped

volumes:
  db_data:

networks:
  internal:
    driver: bridge
